version: '3'
services:
  ece4078-jupyterlab:
    build: .
    user: root
    ports:
      - 8888:8888
      - 8080-8089:8080-8089
    container_name: ece4078-prac
    volumes:
      - ./:/home/ece4078/local
    command: "jupyter lab \
      --NotebookApp.notebook_dir=/home/ece4078/local \
      --NotebookApp.default_url=/lab/ \
      --ip=0.0.0.0 \
      --allow-root \
      --port=8888"
    
